version: '3'
services:
  qupload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qupload
    image: qupload
    restart: always
    ports:
      - "8004:8000"
    volumes:
      - /var/log/qupload:/var/log/qupload
      - /var/www/qupload/media:/app/media
    env_file:
      - .env
